import "./globals.css";

import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";

import { ThemeProvider } from "@/components/theme-providers";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "600"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Money Manager",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={cn(
          fontSans.variable,
          "min-h-dvh bg-background font-sans antialiased"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
