import "./globals.css";

import type { Metadata } from "next";
import { Poppins as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "600"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Money Manager",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={cn(
          fontSans.variable,
          "bg-background min-h-dvh font-sans antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
